sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zhangchen618
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: ql-web-framework01
    access-key-id: LTAI5tM6N5vy1XAWKWL6ptSC
    access-key-secret: SNw9I6cxd4RZtkjjIeaEyFFHzFFyE8
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx2386d4718d22079a
    secret: 3dad54fb3792989d0da41f984c2c5eb5
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem #已认证商家小程序可获取
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem #已认证商家小程序可获取
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php